#enviroment variables

from os import environ

#postgress database
POSTGRES_DATABASE_HOST ="localhost" #environ.get("POSTGRES_DATABASE_HOST")
POSTGRES_DATABASE_NAME ="opendata"  #environ.get("POSTGRES_DATABASE_NAME")
POSTGRES_DATABASE_USER = "postgres"   #environ.get("POSTGRES_DATABASE_USER")
POSTGRES_DATABASE_PORT ="5432"          #environ.get("POSTGRES_DATABASE_PORT")
POSTGRES_DATABASE_PASSWORD ="root"         #environ.get("POSTGRES_DATABASE_PASSWORD")


#mongodb database
MONGODB_DATABASE_HOST = environ.get("MONGODB_DATABASE_HOST")
MONGODB_DATABASE_NAME = environ.get("MONGODB_DATABASE_NAME")
MONGODB_DATABASE_USER = environ.get("MONGODB_DATABASE_USER")
MONGODB_DATABASE_PORT = environ.get("MONGODB_DATABASE_PORT")
MONGODB_DATABASE_PASSWORD = environ.get("MONGODB_DATABASE_PASSWORD")

